name: pcd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - pip
  - psycopg2-binary      # Postgres DB driver
  - gunicorn             # production WSGI server
  - flask-migrate        # DB migrations
  - python-dotenv        # .env support
  - pandas
  - numpy
  - watchdog
  - pip:
    - authlib==1.3.2
    - requests==2.32.3
    - flask_sqlalchemy
    - flask-cors
    - flask-login
    - requests
    - pytest
    - black
    - ollama
    - groq
    - pymupdf
    - pypdf[image]
    - pygltflib
    - reportlab
    - whitenoise
    - boto3
    - google-genai

  # add other pip deps here
